export const SET_TRIP="SET_TRIP";
export const UPDATE_TRIP="UPDATE_TRIP";

export const SET_TITLE="SET_TITLE";
export const UPDATE_TITLE="UPDATE_TITLE";

export const ADD_TRIP_DETAILS="ADD_TRIP_DETAILS";
export const UPDATE_TRIP_DETAILS= "UPDATE_TRIP_DETAILS";

export const ADD_SCHEDULE="ADD_SCHEDULE";
export const UPDATE_SCHEDULE="UPDATE_SCHEDULE";

export const ADD_RESPONSIB="ADD_RESPONSIB";
export const UPDATE_RESPONSIB="UPDATE_RESPONSIB";

export const REGISTER = "REGISTER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

export const SIGN_IN ="SIGN_IN";
export const SIGN_IN_FAILED ="SIGN_IN_FAILED";
export const SIGN_IN_SUCCESS ="SIGN_IN_SUCCESS";
export const SIGN_IN_REQUEST ="SIGN_REQUEST";

export const SIGN_OUT ="SIGN_OUT";
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';
export const SIGN_OUT_REQUEST ="SIGN_OUT_REQUEST";

export const REMOVE_ERROR ='REMOVE_ERROR';
export const ADD_DAYS = 'ADD_DAYS';
